#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     ML,            tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     BL,            tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     FR,            tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     MR,            tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BR,            tmotorNone, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Local Variables////////////////////////////////////////////

//Includes///////////////////////////////////////////////////

#include "JoystickDriver.c"
#include "drive.h"

//Initialize/////////////////////////////////////////////////

void initializeRobot(){
	nMotorEncoder[ML] = 0; // set encoder value to zero
}

//Main Task/////////////////////////////////////////////////

task main(){

	getJoystickSettings(joystick); //courtesy setup//
	initializeRobot();

	while(true){

		//Get Readings//////////////////////////////////////////
		getJoystickSettings(joystick);
		int IR = SensorValue[IRSeeker];
		int wheelEncoder = nMotorEncoder[ML];

		//Display Diagnostics///////////////////////////////////
		nxtDisplayBigTextLine(2, "%i", wheelEncoder); // print wheel Encoder value on line 2

		//Drive/////////////////////////////////////////////////

		driveArcade(joystick.joy1_x1,joystick.joy1_y1,joystick.joy1_x2,joystick.joy1_y2); //drive using the drive function in drive.h

		//Button Movements/////////////////////////////////////

		if(joy1Btn(1) == 1){ //if button one is pressed (1) jog the front motors. 0 is off for buttons
			motor[FL] = 100;
			motor[FR] = 100;
		}
		if(joy1Btn(2) == 1){ //if button one is pressed (1) set the servo to home position
			servo[servo1] = 0;
		}
	}
}
