#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ,               sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     MidLeft,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FrontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     MidRight,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     BackLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Arm,           tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     BackRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     Joint,         tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool jointCheck = false;
bool armCheck = false;

task main(){

	while(jointCheck == false){

		//get Mux value
			int nButtonsMask;
			nButtonsMask = SensorValue[S4];

		motor[Joint] = -35;
		if (nButtonsMask & 0x04){
						motor[Joint] = 0;
						nMotorEncoder[Joint] = 0;
						jointCheck = true;
		}

	}

	while(armCheck == false){

		//get Mux value
			int nButtonsMask;
			nButtonsMask = SensorValue[S4];

		motor[Arm] = -50;
		if (nButtonsMask & 0x02){
						motor[Arm] = 0;
						nMotorEncoder[Arm] = 0;
						armCheck = true;
		}

	}


}
