#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ,               sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     MidLeft,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FrontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     MidRight,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     BackLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Arm,           tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     BackRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     Joint,         tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Local Variables///////////////////////////////////////////

int armStop;
int jointStop;
int lastJoint;
int lastArm;
int currentHeight;
int nButtonsMask;
int IR;

//Include Files////////////////////////////////////////////

#include "JoystickDriver.c"
#include "constantsbowledover.h"
#include "menu.h"
#include "gyro.h"
#include "drivesystem.h"
#include "tasksJoint.h"
#include "tasksArm.h"

//Initilize Robot//////////////////////////////////////////

void initializeRobot()
{
	  nMotorEncoder[Arm] = 0;
	  nMotorEncoder[Joint] = 0;
	  lastJoint = 0;
	  lastArm = 0;
	  currentHeight = 0;
}

//Task Main////////////////////////////////////////////////

task main()
{
			getJoystickSettings(joystick);
			initializeRobot();

	while(true)
		{
			//get Mux value
			nButtonsMask = SensorValue[S4];

			IR = SensorValue[IRSeeker];
			//nxtDisplayBigTextLine(0, "%i", IR);

			// Get joystick settings and display encoder value.
			getJoystickSettings(joystick);
			int armEncoder = nMotorEncoder[Arm];
			int jointEncoder = nMotorEncoder[Joint];
			//encoder = encoder * -1;
			nxtDisplayBigTextLine(2, "%i", armEncoder);
			nxtDisplayBigTextLine(4, "%i", jointEncoder);
			//nxtDisplayBigTextLine(2, "%i", Left);
			//nxtDisplayBigTextLine(4, "%i", Right);

		  if(joystick.joy1_x2 < -35){

		  	motor[FrontRight] = 90;
      	motor[BackRight] = 90;
      	motor[MidRight] = 90;
      	motor[FrontLeft] = -90;
      	motor[BackLeft] = -90;
      	motor[MidLeft] = -90;

			}

			if(joystick.joy1_x2 > 35){

		  	motor[FrontRight] = -90;
      	motor[BackRight] = -90;
      	motor[MidRight] = -90;
      	motor[FrontLeft] = 90;
      	motor[BackLeft] = 90;
      	motor[MidLeft] = 90;

			}

////DRIVE SPEED/////////////////////////////////

   		switch (joystick.joy1_TopHat)
   		{

   		case 0:  //up
		    fineDriveMode = false;
		    mediumDriveMode = false;
		    break;
		  case 2:  //right
		    fineDriveMode = false;
		    mediumDriveMode = true;
		    break;
		  case 4:  //down
		    fineDriveMode = true;
		    mediumDriveMode = false;
		    break;
		  case 6:  //left
		  	fineDriveMode = false;
		    mediumDriveMode = true;
		    break;
		  default: //anything else
		    break;
	    }


////Driver 1 ENCODER ARM HEIGHTS/////////////////////////

				if(joy1Btn(1) == 1 && btnLastState[1] == 0) //Dispenser Height
				{
					armTaskRunning = true;
					jointTaskRunning = true;
					armStop = 150;
					jointStop = 1000;
					runArm();

				}

				if(joy1Btn(2) == 1 && btnLastState[2] == 0) //Low Scoring Zone
				{
					armTaskRunning = true;
					jointTaskRunning = true;
					armStop = 1300;
					jointStop = 1400;
					runArm();

				}

				if(joy1Btn(3) == 1 && btnLastState[3] == 0) //Middle Scoring Zone
				{
					armTaskRunning = true;
					jointTaskRunning = true;
					armStop = 4350;
					jointStop = 2250;
					runArm();
				}

				if(joy1Btn(4) == 1 && btnLastState[4] == 0) //High Scoring Zone
				{
					armTaskRunning = true;
					jointTaskRunning = true;
					armStop = 7250;
					jointStop = 3150;
					runArm();
				}

////MANUAL MOVEMENT OF ARM//////////////////////////

				if(joy1Btn(5) == 1)
		 		{
		 			armTaskRunning = false;
		 			jointTaskRunning = false;
		 			motor[Arm] = -35;
		 			wait10Msec(2);
				}

				if(joy1Btn(6) == 1)
				{
					armTaskRunning = false;
					jointTaskRunning = false;
					motor[Arm] = 85;
					wait10Msec(2);
				}

//Power off when not referenced////////////////////////////

				if(joy1Btn(5) == 0 && joy1Btn(6) == 0 && joy2Btn(5) == 0 && joy2Btn(6) == 0 && armTaskRunning == false)
				{
					motor[Arm] = 0;
					wait10Msec(1);
				}

				if(joy1Btn(7) == 0 && joy1Btn(8) == 0 && joy1Btn(9) == 0 &&  joy1Btn(10) == 0 && joy2Btn(7) == 0 && joy2Btn(8) == 0 && joy2Btn(9) == 0 &&  joy2Btn(10) == 0 && jointTaskRunning == false)
				{
					motor[Joint] = 0;
					wait10Msec(1);
				}

////RESET ARM WITH MULTIPLEXOR////////////////////////////
				//can be 01 02 04 and 08
				if (nButtonsMask & 0x02){

					if(armEncoder != 0){
						nMotorEncoder[Arm] = 0;
					}
	  		}

	  		if (nButtonsMask & 0x04){

					if(jointEncoder != 0){
						nMotorEncoder[Joint] = 0;
				}

	  		}

////MANUAL COMBINED MOVEMENT FOR SCORING///////////////////
	  		if(joy1Btn(8) == 1){

					armTaskRunning = false;
					jointTaskRunning = false;
		 			StopTask(armRaise);
		 			StopTask(armLower);
		 			StopTask(jointRaise);
		 			StopTask(jointLower);
					motor[Arm] = 60;
					motor[Joint] = -25;
					wait1Msec(2);
				}

	  if(joy1Btn(7) == 1){

					armTaskRunning = false;
					jointTaskRunning = false;
					StopTask(armRaise);
		 			StopTask(armLower);
		 			StopTask(jointRaise);
		 			StopTask(jointLower);
					motor[Arm] = -85;
					motor[Joint] = 20;
					wait1Msec(2);
				}

//MANUAL JOINT MOVEMENT///////////////////////////

				if(joy1Btn(9) == 1){

					motor[Joint] = 45;
					wait10Msec(1);
				}

				if(joy1Btn(10) == 1){

					motor[Joint] = -45;
					wait10Msec(1);
				}



////DRIVING//////////////////////////////////////

			if(joystick.joy1_x1 > -15 && joystick.joy1_x1 < 15 && joystick.joy1_y1 > -15 && joystick.joy1_y1 < 15)
    	{
      	motor[FrontRight] = 0;
      	motor[BackRight] = 0;
      	motor[MidRight] = 0;
      	motor[FrontLeft] = 0;
      	motor[BackLeft] = 0;
      	motor[MidLeft] = 0;
    	}

		  DriveArcade(NORMALIZE_DRIVE(DEADBAND_INPUT(joystick.joy1_y1), -128, 127), NORMALIZE_DRIVE(DEADBAND_INPUT(joystick.joy1_x1), -128, 127));
////////////////////////////////////CONTROLLER 2/////////////////////////////////////////////////////////////



	if(joy2Btn(1) == 1) //Dispenser Height
				{
					armTaskRunning = true;
					jointTaskRunning = true;
					armStop = 150;
					jointStop = 1000;
					runArm();

				}

				if(joy2Btn(2) == 1) //Low Scoring Zone
				{
					armTaskRunning = true;
					jointTaskRunning = true;
					armStop = 1300;
					jointStop = 1400;
					runArm();

				}

				if(joy2Btn(3) == 1) //Middle Scoring Zone
				{
					armTaskRunning = true;
					jointTaskRunning = true;
					armStop = 4350;
					jointStop = 2250;
					runArm();
				}

				if(joy2Btn(4) == 1) //High Scoring Zone
				{
					armTaskRunning = true;
					jointTaskRunning = true;
					armStop = 7250;
					jointStop = 3150;
					runArm();
				}

////MANUAL MOVEMENT OF ARM//////////////////////////

				if(joy2Btn(5) == 1)
		 		{
		 			armTaskRunning = false;
		 			motor[Arm] = -35;
		 			wait10Msec(2);
				}

				if(joy2Btn(6) == 1)
				{
					armTaskRunning = false;
					motor[Arm] = 85;
					wait10Msec(2);
				}


////MANUAL COMBINED MOVEMENT FOR SCORING///////////////////
	  		if(joy2Btn(8) == 1){

					armTaskRunning = false;
		 			StopTask(armRaise);
		 			StopTask(armLower);
		 			StopTask(jointRaise);
		 			StopTask(jointLower);
					motor[Arm] = 60;
					motor[Joint] = -35;
					wait10Msec(1);
				}

	  if(joy2Btn(7) == 1){

					armTaskRunning = false;
					StopTask(armRaise);
		 			StopTask(armLower);
		 			StopTask(jointRaise);
		 			StopTask(jointLower);
					motor[Arm] = -50;
					motor[Joint] = 35;
					wait10Msec(1);
				}

//MANUAL JOINT MOVEMENT///////////////////////////

				if(joy2Btn(9) == 1){

					motor[Joint] = 45;
					wait10Msec(1);
				}

				if(joy2Btn(10) == 1){

					motor[Joint] = -45;
					wait10Msec(1);
				}


	}
}
